### PR TITLE
rectify collision detection on lines

### PR DESCRIPTION
**Pull request by madduccino**
#221 - 'Lines' drawn as rectangles and rotated. Further tested on Fly Trap game: http://bit.ly/2qg509N

### CODE REVIEW

**Comment by stevekrouse** [comment]
**[This is an automated integration to preview this pull request's changes to the website.]**

https://cdn.rawgit.com/stevekrouse/WoofJS/b7a5dd649323a93adc8b2dc08a9b4f85a9e4e754/index.html

**Comment by madduccino** [comment]
As it turns out, the user actually can't rotate the line. But I think that's fine because they don't need to, right? Gave the comments a shot.

**Comment by stevekrouse** [comment]
Yes, I think you're correct... I can imagine a scenario where a user would want to create a line (or rectangle) by one endpoint and an angle and a length, but we don't have to deal with that here.

Can you make it throw an error when the user tries to set the angle of a line sprite? You can see an example of this when the user tries to set the line height https://github.com/stevekrouse/WoofJS/pull/376/files#diff-5338d6ced086475e03af0133a2630e99R1088

**Comment by madduccino** [comment]
@stevekrouse this one should be ready to merge? I'd love to have it by tomorrow as I have a student working on the fly trap game!

**Pull request merged**
