### PR TITLE
epic sound library

### PR DESCRIPTION
**Pull request by nicolekelner**
New sounds and custom icons for the sounds

### CODE REVIEW

**Comment by stevekrouse** [comment]
**[This is an automated integration to preview this pull request's changes to the website.]**

https://cdn.rawgit.com/stevekrouse/WoofJS/f38731d0440e917ff13274d75d1360b432812d1a/index.html

**Comment by stevekrouse** [comment]
I'm confused. Is this pull request instead of https://github.com/stevekrouse/WoofJS/pull/354? Why didn't you just add another commit to the original pull request?

**Comment by nicolekelner** [comment]
I think this was because I had worked on an old version of the code so you
wanted me to start fresh once I pulled!

**Comment by stevekrouse** [comment]
Ah, I see that now. In the future, it would make sense to explain this in your new pull request by referencing the old pull request as well as closing the old pull request.

**Comment by stevekrouse** [comment]
Good catch on the `switch` sound!

**Pull request merged**
