### PR TITLE
Puts if condition within comments

### PR DESCRIPTION
**Pull request by lewi-g**

### CODE REVIEW

**Comment by stevekrouse** [comment]
**[This is an automated integration to preview this pull request's changes to the website.]**

https://cdn.rawgit.com/lewi-g/WoofJS/363b32414b68753bdda89ba19494c92af6be6891/index.html

**Comment by lewi-g** [comment]
I read the comments in #521 and realized the comment might have been left there intentionally for the students to ask questions and learn. Is that true?

**Comment by stevekrouse** [comment]
hey @lewi-g! Thanks for contributing. Question for you - how did you do this so fast? I literally just merged in this change a few minutes before your pull request.

The reason that we left the `true` outside the comment was to stop the errors that it caused by adding if-statements without anything inside the parenthesis to the editor. 

image

**Comment by lewi-g** [comment]
@stevekrouse I am a teacher at the coding space and work on curriculum ideas with the team. One of our teachers pointed it out to me and I had a little time before a class started to see if I can address it. 

Thanks for telling me why you chose the action you did. I'm curious to see if students will notice and delete 'true' even if it's not within comments. It should lead to some learning. :)

**Pull request closed without merging**
