### PR TITLE
add function to detect mobile device

### LINKED ISSUE #174: "mobile" should be a boolean the evaluates to whether the user is on a mobile device

### PR DESCRIPTION
**Pull request by joebeachjoebeach**
`mobile()` returns `true` if the user is on a mobile device -- added it to "sensing" in the documentation 

closes #174

### CODE REVIEW

**Comment by stevekrouse** [comment]
View this pull request at:

https://cdn.rawgit.com/stevekrouse/WoofJS/1781fb2e2f69214b0b567d15fb983a1816de42e3/index.html

**Comment by stevekrouse** [comment]
Nice! This will be a useful function.

This function either returns `null` or an error for me on my iphone on chrome and safari. I think the `.match` function and `||` operators aren't doing what you expect them to.

Also, be sure to add `mobile()` to the autocomplete suggestions.

**Comment by joebeachjoebeach** [comment]
@stevekrouse thanks for the feedback. Yeah, it works on Chrome on my Android, but I figured there may be issues elsewhere as I can't test on other mobile devices. I'll see what I can do

**Comment by stevekrouse** [comment]
Beautiful! Love that you included the link to the place you got the function from.

**Pull request merged**
