### PR TITLE
Clarify git instructions

### PR DESCRIPTION
**Pull request by the-viking**
For the readme, adds a step in the contributing instructions for staging changes and links the small license image at the top of the page to the license.

### CODE REVIEW

**Comment by stevekrouse** [comment]
**[This is an automated integration to preview this pull request's changes to the website.]**

https://cdn.rawgit.com/the-viking/WoofJS/f32281109f53fff0b7f01e87ca1a7f291a3a5d7b/index.html

**Comment by the-viking** [comment]
Thanks for the help! I just submitted a new pull request with those changes, let me know if I got everything

**Comment by the-viking** [comment]
Thanks for the help! I just submitted a pull request with these changes, let me know if I got everything.

**Comment by stevekrouse** [comment]
👍

**Pull request merged**
